# Generated by Django 5.1.4 on 2024-12-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firehazardresponder',
            old_name='emergency_contact2',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='firehazardresponder',
            old_name='emergency_contact1',
            new_name='phonecall_contact',
        ),
        migrations.RenameField(
            model_name='firehazardresponder',
            old_name='emergency_contact3',
            new_name='sms_contact',
        ),
        migrations.RenameField(
            model_name='medicalresponder',
            old_name='emergency_contact2',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='medicalresponder',
            old_name='emergency_contact1',
            new_name='phonecall_contact',
        ),
        migrations.RenameField(
            model_name='medicalresponder',
            old_name='emergency_contact3',
            new_name='sms_contact',
        ),
        migrations.RenameField(
            model_name='securityresponder',
            old_name='emergency_contact2',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='securityresponder',
            old_name='emergency_contact1',
            new_name='phonecall_contact',
        ),
        migrations.RenameField(
            model_name='securityresponder',
            old_name='emergency_contact3',
            new_name='sms_contact',
        ),
    ]
