# Generated by Django 5.1.4 on 2024-12-25 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8dc343ac-21cd-4246-8dde-220f1dafa827'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
