# Generated by Django 5.1.4 on 2024-12-25 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_customusermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf837926-1350-4b54-afdb-2caedf6f47bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
