# Generated by Django 5.1.4 on 2024-12-30 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_alter_customusermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abe70d45-0202-4b70-ad02-4de14c555fa7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
