# Generated by Django 5.1.5 on 2025-01-20 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_input_location', models.CharField(max_length=100)),
                ('live_location', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('incident_date', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
