# Generated by Django 5.2a1 on 2025-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_incident_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('security', 'Security')], default='medical', max_length=50),
        ),
    ]
